### ISSUE TITLE
With Windows

### ISSUE THREAD

**Issue by SirdLay** [ankenyr/jellyfin-youtube-metadata-plugin#100]
Hey How do I use this with my Jellyfin server running on windows ? Not docker 

I tried:

Installed plugin from catalogue.
Downloaded yt-dlp and added path to Environment variable. 

Issue:
'Identify' responds without any data

**Comment by SirdLay** [comment]
[2024-03-17 20:06:05.890 +00:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Provider "YoutubeMetadata" failed to retrieve search results
System.NotImplementedException: The method or operation is not implemented.
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetSearchResults(E searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

**Comment by SirdLay** [comment]
![image](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/assets/115919066/134d416f-e627-4043-b06d-fdebea286511)

**Comment by ankenyr** [comment]
The error makes me think that methods I am using are not compatible with Windows. I don't use Windows and likely will not support it anytime soon.
