### ISSUE TITLE
Error downloading thumbnails/images

### ISSUE THREAD

**Issue by joestump** [ankenyr/jellyfin-youtube-metadata-plugin#109]
Seeing the following:

```
[18:47:23] [ERR] [294] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in YoutubeMetadata
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetYTID(String name)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetMetadata(E info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[18:47:23] [INF] [106] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/YouTube/video/spawnwave/2024-06-05_spawnwave_nintendo-switch-scalpers-get-ridiculous-and-xbox-set-for-a-surprising-hardware-r_SHL9jMr_cKQ_1080p-vp9-opus.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[18:47:23] [ERR] [115] MediaBrowser.Providers.TV.EpisodeMetadataService: Error validating images for Pathfinder Tragedy (1989)
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.Extensions.FileSystemGlobbing.MatcherExtensions.GetResultsInFullPath(Matcher matcher, String directoryPath)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider.GetSeriesInfo(String path)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider.GetImages(BaseItem item, IDirectoryService directoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

It appears to be fetching the title/description just fine. It's also writing to the cache directory. No thumbs though.

**Comment by ankenyr** [comment]
Can you turn on debug logging and provide the logs?
It is looking to me like the object coming from jellyfin itself is not being populated with the correct information needed to do the looksup. This may be a issue outside of this plugin itself.

**Comment by OdinVex** [comment]
I have the same issue, unfortunately, but slightly different source of issue:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.GetYTID(String name)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider.GetImages(BaseItem item, IDirectoryService DirectoryService)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at MediaBrowser.Providers.Manager.ItemImageProvider.ValidateImages(BaseItem item, IEnumerable`1 providers, ImageRefreshOptions refreshOptions)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

Notice it's within GetYTID's calls to regex.
