### ISSUE TITLE
Error in Log: youtube-dl not found on path!

### ISSUE THREAD

**Issue by lamyergeier** [ankenyr/jellyfin-youtube-metadata-plugin#112]
# Error

```
[2024-09-11 11:57:53.050 +00:00] [ERR] [73] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "YoutubeMetadata"
System.IO.FileNotFoundException: youtube-dl not found on path!
   at NYoutubeDL.Services.PreparationService.SetupPrepare(YoutubeDLP ydl)
   at NYoutubeDL.Services.InfoService.GetDownloadInfoAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.PreparationService.PrepareDownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, String url, CancellationToken cancellationToken)
   at NYoutubeDL.YoutubeDLP.DownloadAsync(String videoUrl)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.YTDLMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLMovieProvider.GetAndCacheMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetMetadata(E info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

# Info

```
$ type yt-dlp 
yt-dlp is /home/lamy/opt/bin/yt-dlp
yt-dlp is /home/lamy/.local/bin/yt-dlp
yt-dlp is /usr/bin/yt-dlp
yt-dlp is /home/linuxbrew/.linuxbrew/bin/yt-dlp
```

```
$ docker images
REPOSITORY                     TAG       IMAGE ID       CREATED        SIZE
jellyfin/jellyfin              latest    de4f7879e9d1   3 days ago     1.03GB
```

Installed plugin using: [Recommended method](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin?tab=readme-ov-file#installing-from-repository-recommended)

**Comment by ankenyr** [comment]
Are you doing that type from within the container?

**Comment by lamyergeier** [comment]
yt-dlp is not installed in jellyfin docker container. But in my Fedora 40. Do I need to install yt-dlp in the container? Could you please how can I do it?
