### ISSUE TITLE
System.IO.DirectoryNotFoundException when Scanning Library

### ISSUE THREAD

**Issue by SenpaiSimon** [ankenyr/jellyfin-youtube-metadata-plugin#115]
Hello i have encountered a issue while using the plugin.

I set the plugin up properly, installed yt-dlp, made sure it works, installed python3 and so on.
When scanning the first 50 videos or so went without any error. However after some time the logs got flooded with the same error again and again.

I have included a excerpt from the log file. In the beginning you can see that everything works smoothly and after some time the plugin throws errors.

The plugin is installed in a jellyfin instance running inside a docker container.

[log_20240919.log](https://github.com/user-attachments/files/17059832/log_20240919.log)

**Comment by miguelarios** [comment]
I have the same error. Have you found what is going on? I searched inside the plugins folder and I see that its not working because the folder isn't created the way this plugin says in the logs it expects it but i'm sure why it expects that folder to be written this way.

**Comment by davekaufman** [comment]
same for me here

**Comment by lavilao** [comment]
I fixed it by updating yt-dlp.

**Comment by elulcao** [comment]
I removed the version from package manager and installed via Release:
`https://github.com/yt-dlp/yt-dlp/wiki/Installation`

**Comment by TopoDiFogna** [comment]
I installed everything from scratch today, same issue with latest jellyfin (10.10.7) and yt-dlp (2025.03.31)

Jellyfin is in docker, yt-dlp is mounted, logs repeats for every video, copying one as example:
```
[08:16:19] [ERR] [73] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Movie at /data/media/youtube/ONI - Ultimate Beginner's Guide/Hatch Ranching ｜ Ultimate Beginner's Guide ｜ Ep 8 ｜ ONI [efnjSzea4qk].mkv
System.IO.DirectoryNotFoundException: Could not find a part of the path '/cache/youtubemetadata/efnjSzea4qk/ytvideo.info.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Comment by JordanLawson** [comment]
I have the addon (1.0.3.15), jellyfin and yt-dlp installed via apt, and unfortunately I am having the same type of issue, where no thumbnail image will be loaded.  It would be nice if there was a button somewhere that would ran a test to see if everything related to the addon is working.
I am also having an issue getting the folders of the library to display in a sensible way, I see no guidance on the matter in the readme.

<img width="1548" height="622" alt="Image" src="https://github.com/user-attachments/assets/10499f64-2570-4b1f-a972-10c910e61d13" />

**Comment by ThatFatRat** [comment]
> I have the addon (1.0.3.15), jellyfin and yt-dlp installed via apt, and unfortunately I am having the same type of issue, where no thumbnail image will be loaded. It would be nice if there was a button somewhere that would ran a test to see if everything related to the addon is working. I am also having an issue getting the folders of the library to display in a sensible way, I see no guidance on the matter in the readme.
> 
> <img alt="Image" width="1548" height="622" src="https://private-user-images.githubusercontent.com/46769085/561949159-10499f64-2570-4b1f-a972-10c910e61d13.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MjI4MTQsIm5iZiI6MTc3MzcyMjUxNCwicGF0aCI6Ii80Njc2OTA4NS81NjE5NDkxNTktMTA0OTlmNjQtMjU3MC00YjFmLWE5NzItMTBjOTEwZTYxZDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzE3VDA0NDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZmM2MTUwZjgyZmM1OTVkOGVjZDQ5MmVjYTEzZjNkNDNlNmY0ZTc0NmMzYjQ2Y2NiY2QzZGUxYmE4ZmUzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EJOyu0yOjvhe51Bm-tHSYQ7f73Te1qDHIWAuZJFieag">

After a lot of fooling around I found out YouTube was kicking off verification and my cookies.txt file was not being used. It turns out this plugin does not use the correct path instead it reads /var/lib/jellyfin/plugins/cookies.txt
Once I put my cookies.txt file there the plugin started working.
