### ISSUE TITLE
No metadata is downloaded

### ISSUE THREAD

**Issue by TheFrenchGhosty** [ankenyr/jellyfin-youtube-metadata-plugin#13]
I'm guessing this issue is related to https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/11

I installed the addon, added the dll linked in https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/11#issuecomment-664143899 and it's correctly appearing in the plugin list, I added my API key and created a library with the right settings, however absolutely no metadata seems to be downloaded.

Example:

Filename: Linus Tech Tips - 20200724 - Oh No Intel!! NOT AGAIN - WAN Show July 24, 2020 [kt78qhcnmQo].mkv

Downloaded with my script: https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/blob/master/Linux%20-%20OSX/Watch%20on%20Mobile%20Devices%20Script/Watch%20on%20Mobile%20Devices.sh

![screenshot](https://user-images.githubusercontent.com/47571719/90989187-468a4080-e588-11ea-88eb-d94d8fc19cb2.png)

**Comment by TheFrenchGhosty** [comment]
Some logs (I redacted the personal data):

```

[2020-08-24 00:33:32.375 +02:00] [INF] [73] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: /path/to/YouTube/[VIDEO1].mkv
[2020-08-24 00:33:32.426 +02:00] [INF] [21] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalProvider: Could not find "/path/to/YouTube/[VIDEO1].mkv"
[2020-08-24 00:33:32.426 +02:00] [INF] [21] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: 7_5m98KW4Dc
[2020-08-24 00:33:32.426 +02:00] [INF] [21] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: In DownloadInfo
[2020-08-24 00:33:42.582 +02:00] [ERR] [21] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "YouTube Metadata"
The service youtube has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
YouTube Data API v3 has not been used in project [ID] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=[ID] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
	Message[YouTube Data API v3 has not been used in project [ID] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=[ID] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync()
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.DownloadInfo(String youtubeId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2020-08-24 00:33:42.790 +02:00] [INF] [21] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: /path/to/YouTube/[VIDEO2].mkv
[2020-08-24 00:33:42.848 +02:00] [INF] [6] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalProvider: Could not find "/path/to/YouTube/[VIDEO2].mkv"
[2020-08-24 00:33:42.848 +02:00] [INF] [6] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: 3YFeE1eDlD0
[2020-08-24 00:33:42.848 +02:00] [INF] [6] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: In DownloadInfo
[2020-08-24 00:33:52.896 +02:00] [ERR] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "YouTube Metadata"
The service youtube has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
YouTube Data API v3 has not been used in project [ID] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=[ID] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
	Message[YouTube Data API v3 has not been used in project [ID] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=[ID] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync()
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.DownloadInfo(String youtubeId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by ankenyr** [comment]
The slowness is due to limits on the API. There are only so many requests you can do in a day and to prevent exceeding quota I put in a limiter.

For the latest stuff that looks to be downloading metadata but not images. Is it still saying a line like
 Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalProvider: Could not find "/path/to/YouTube/[VIDEO] [ID].mkv"
There are two providers, one is remote and another is local. Local looks on the file system for an image with the same filename but with .jpg extension to provide the file. It is strange it is prefering that over the remote considering you provided it with an API key.

**Comment by TheFrenchGhosty** [comment]
Okay, so I recreated a collection (I was using the existing one).

Properly configured it so that YouTubeMetadata is the only thing used for metadata and images, and well, new thing in the log:

```
[2020-08-24 01:57:23.493 +02:00] [ERR] [37] MediaBrowser.Providers.Manager.ProviderManager: "YoutubeMetadataImageProvider" failed in GetImageInfos for type "Movie"
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.GetPathByTitle(String title)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider.GetYTID(String title)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type) in /home/[USERNAME]/.cache/yay/jellyfin/src/jellyfin-10.6.3/MediaBrowser.Providers/Manager/ProviderManager.cs:line 261
```

Okay, so about the stuff in .cache/yay/jellyfin, it's a weird issue.

In short: my Jellyfin is running on Arch, and I used the AUR package to install it, I then deleted the cache folder where it was build (yay/jellyfin), but for whatever reason Jellyfin is sometimes complaining that it's missing.

I will do some research about that, but in the meantime, do you think those deleted files are the issue?

**Comment by TheFrenchGhosty** [comment]
Problem solved, this was because the AUR package ```jellyfin``` is broken, I moved to the 2 binary packages provided by the jellyfin team and everything is working.

I opened a PR about the missing setup step https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/pull/14 because that was the first issue.

Everything is perfectly working now!
