### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by bradbeattie** [ankenyr/jellyfin-youtube-metadata-plugin#35]
Hmm... I know it _was_ working earlier this evening. I can confirm I have my API token in place. I'm unclear what `Value cannot be null. (Parameter 's')` infers here. Is that the `--simulate` flag on youtube-dl? Odd...

The following error occurs when I try to refresh the metadata on my library content:

```
jellyfin_1  | [03:11:46] [INF] [100] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: /media/TubeSync/downloads/video/veritasium-selected/2011-02-17_veritasium-selected_how-far-away-is-the-moon-the-scale-of-the-universe_[Bz9D6xba9Og].mkv
jellyfin_1  | [03:11:46] [INF] [98] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: Bz9D6xba9Og
jellyfin_1  | [03:11:46] [ERR] [98] MediaBrowser.Providers.Movies.MovieMetadataService: Error in YouTube-DL Metadata
jellyfin_1  | System.ArgumentNullException: Value cannot be null. (Parameter 's')
jellyfin_1  |    at Jellyfin.Plugin.YoutubeMetadata.Utils.MovieJsonToMovie(YTDLMovieJson json)
jellyfin_1  |    at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDLMetadataProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

Any insight here?

Further noting that `/cache/youtubemetadata/<youtube id>/ytvideo.info.json` is properly populated after the fetch.

**Comment by ankenyr** [comment]
Which version of the plugin are you on?

**Comment by ankenyr** [comment]
Can you also provide the json as found in the cache? The error indicates to me that it has something to do with that json.

**Comment by bradbeattie** [comment]
```
jellyfin_1  | [02:17:04] [INF] [141] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: /media/TubeSync/downloads/video/veritasium-selected/2011-02-17_veritasium-selected_how-far-away-is-the-moon-the-scale-of-the-universe_[Bz9D6xba9Og].mkv
jellyfin_1  | [02:17:04] [ERR] [242] MediaBrowser.Providers.Movies.MovieMetadataService: Error in YouTube-DL Metadata
jellyfin_1  | System.ArgumentNullException: Value cannot be null. (Parameter 's')
jellyfin_1  |    at Jellyfin.Plugin.YoutubeMetadata.Utils.MovieJsonToMovie(YTDLMovieJson json)
jellyfin_1  |    at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDLMetadataProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
jellyfin_1  | [02:17:04] [INF] [242] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeMetadataProvider: Bz9D6xba9Og
jellyfin_1  | [02:17:04] [INF] [242] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalProvider: Could not find /media/TubeSync/downloads/video/veritasium-selected/2011-02-17_veritasium-selected_how-far-away-is-the-moon-the-scale-of-the-universe_[Bz9D6xba9Og].mkv
jellyfin_1  | [02:17:04] [ERR] [242] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Movie at /media/TubeSync/downloads/video/veritasium-selected/2011-02-17_veritasium-selected_how-far-away-is-the-moon-the-scale-of-the-universe_[Bz9D6xba9Og].mkv
jellyfin_1  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin_1  |    at Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
jellyfin_1  |    at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

```
# cat Bz9D6xba9Og/ytvideo.info.json
{"AgeGating":null,"ContentDetails":null,"ETag":"eQj9EZp7LIWloDSMAEkD7lY6rkw","FileDetails":null,"Id":"Bz9D6xba9Og","Kind":"youtube#video","LiveStreamingDetails":null,"Localizations":null,"MonetizationDetails":null,"Player":null,"ProcessingDetails":null,"ProjectDetails":null,"RecordingDetails":null,"Snippet":{"CategoryId":"27","ChannelId":"UCHnyfMqiRRG1u-2MsSQLbXA","ChannelTitle":"Veritasium","DefaultAudioLanguage":null,"DefaultLanguage":"en","Description":"If the Earth were the size of a basketball and the moon a tennis ball, how far apart would they be? Diagrams that are not to scale make us think that they\u0027re closer than they really are.","LiveBroadcastContent":"none","Localized":{"Description":"If the Earth were the size of a basketball and the moon a tennis ball, how far apart would they be? Diagrams that are not to scale make us think that they\u0027re closer than they really are.","Title":"How Far Away is the Moon? (The Scale of the Universe)","ETag":null},"PublishedAtRaw":"2011-02-17T15:24:41Z","PublishedAt":"2011-02-17T15:24:41+00:00","Tags":["moon","earth","scale model","scale of the universe","solar system model","science literacy","moon\u0027s orbit"],"Thumbnails":{"Default__":{"Height":90,"Url":"https://i.ytimg.com/vi/Bz9D6xba9Og/default.jpg","Width":120,"ETag":null},"High":{"Height":360,"Url":"https://i.ytimg.com/vi/Bz9D6xba9Og/hqdefault.jpg","Width":480,"ETag":null},"Maxres":{"Height":720,"Url":"https://i.ytimg.com/vi/Bz9D6xba9Og/maxresdefault.jpg","Width":1280,"ETag":null},"Medium":{"Height":180,"Url":"https://i.ytimg.com/vi/Bz9D6xba9Og/mqdefault.jpg","Width":320,"ETag":null},"Standard":{"Height":480,"Url":"https://i.ytimg.com/vi/Bz9D6xba9Og/sddefault.jpg","Width":640,"ETag":null},"ETag":null},"Title":"How Far Away is the Moon? (The Scale of the Universe)","ETag":null},"Statistics":null,"Status":null,"Suggestions":null,"TopicDetails":null}
```

Jellyfin 10.7.7, plugin 1.0.3.2.

**Comment by bradbeattie** [comment]
And note that while it says it "Could not find" the video in question, I `docker exec`'d my way into the running container and confirmed it was indeed there and readable. :shrug:

**Comment by ankenyr** [comment]
Weird, will see if I can test this out a bit tonight. Full disclosure. I am
making some improvements and am almost ready to push. This will be
compatible with 10.8 after that though.

**Comment by bradbeattie** [comment]
Yeah. The behaviour is _odd_ as I can get it to _sometimes_ work depending on the files I expose in the attached media folder, but nothing conclusive so far.

If the easier answer is "release the new version and see if the bug persists", I'm happy to delay. I wouldn't want you to invest time in something that might already be resolved!

**Comment by ankenyr** [comment]
Can you tell me more about the files exposed vs not exposed that you are
switching?

**Comment by bradbeattie** [comment]
I just tried replicating from scratch and found that it's not the addition or removal of media, but the renaming of the library from `Movies1` to `YouTube`. That renaming breaks all the metadata and "Refresh all metadata" generates the above errors for any and all media. Renaming the library back to `Movies1` does _not_ rectify the problem. Interesting...

**Comment by ankenyr** [comment]
Hi @bradbeattie
I made some large changes, if you are on 10.8 you can use the newest version of the plugin. Let me know if you continue to get errors.

**Comment by ankenyr** [comment]
Hi Brad, I am going to close this issue assuming it is fixed on the latest version. Please reopen if it is not.
