### ISSUE TITLE
Some thumbnails not showing

### ISSUE THREAD

**Issue by FunDeckHermit** [ankenyr/jellyfin-youtube-metadata-plugin#42]
**Setup**
I have youtube-DL configured to output info.json files and thumbnails with the same filename as the video. The Jellyfin library is only using the YouTube-DL Image Metadata provider wherever possible. 
Jellyfin running on Docker and all volumes are owned by the jellyfin user. 

Screenshot of Jellyfin with two video's lacking thumbnails.
![image](https://user-images.githubusercontent.com/5075692/154860334-380e0f85-8d21-4e82-9fef-6046b3d35f7e.png)

The files on the filesystem look perfect to me:
![image](https://user-images.githubusercontent.com/5075692/154860443-75e2a39b-089f-42cc-9302-aa62ef30fe16.png)

Looking at the logs show some funky business: [Full Log](https://gist.github.com/mindfuucker/0e8726f50e0d30b4db707e9704e7e0fd)
```
[2022-02-20 19:26:07.347 +00:00] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: "YTDLImageProvider" failed in GetImageInfos for type "Movie" at "/media/Gold Shaw Farm/How to Build a Farm in 6 MONTHS [UVTks4xacsg].mp4"
System.IO.FileNotFoundException: youtube-dl not found on path!
   at NYoutubeDL.Services.PreparationService.SetupPrepare(YoutubeDL ydl)
   at NYoutubeDL.Services.InfoService.GetDownloadInfoAsync(YoutubeDL ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.PreparationService.PrepareDownloadAsync(YoutubeDL ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDL ydl, CancellationToken cancellationToken)
   at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDL ydl, String url, CancellationToken cancellationToken)
   at NYoutubeDL.YoutubeDL.DownloadAsync(String videoUrl)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.YTDLMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Comment by ankenyr** [comment]
Can you show me what the settings look like for the library?

**Comment by mindfuucker** [comment]
Hello Rob, 

Here are screenshots if my library:

|  |  | |
| --- | --- | --- | 
| ![1645431146946](https://user-images.githubusercontent.com/5075692/154914476-62ab4f99-9b9e-4848-b108-29379da2ea75.jpg) | ![1645431146874](https://user-images.githubusercontent.com/5075692/154914478-f5b858c6-2c78-4bcc-ac5d-30a56c8dda19.jpg) | ![1645431146889](https://user-images.githubusercontent.com/5075692/154914481-847d58ee-6256-4cdb-9b3b-d85aa56fc1e4.jpg) |
| ![1645431146904](https://user-images.githubusercontent.com/5075692/154914483-84664167-4256-4c39-bd38-08cb1be05caa.jpg) | ![1645431146918](https://user-images.githubusercontent.com/5075692/154914487-381b741a-1b76-4c05-8eb3-2d741bc051c6.jpg) | ![1645431146931](https://user-images.githubusercontent.com/5075692/154914490-bb0a5797-fa36-42f0-b286-61e36d3d55fc.jpg) |

**Comment by ankenyr** [comment]
The error log saying `youtube-dl not found on path` leads me to believe that you do not have yt-dlp installed. Is this in a docker container? Can you confirm that yt-dlp is installed and available to jellyfin?

**Comment by FunDeckHermit** [comment]
Hello @ankenyr,

I can't even remember running this plugin. Troubleshooting would be difficult. My whole setup is nuked already.
Thanks for the reply though
