### ISSUE TITLE
[1.0.3.6] Regression - Failed to load assembly "Jellyfin.Plugin.YoutubeMetadata.dll"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [ankenyr/jellyfin-youtube-metadata-plugin#48]
Regression after updating to 1.0.3.6, from 1.0.3.5.

Using the Jellyfin docker image `jellyfin/jellyfin:10.8.0-beta2`

```
[ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/var/lib/jellyfin/plugins/YoutubeMetadata_1.0.3.6/Jellyfin.Plugin.YoutubeMetadata.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ExecuteAsync' in type 'Jellyfin.Plugin.YoutubeMetadata.EpisodeIndexer' from assembly 'Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.YoutubeMetadata.EpisodeIndexer' from assembly 'Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by TheFrenchGhosty** [comment]
After testing with @ankenyr this is fixed in 1.0.3.7
