### ISSUE TITLE
Could not find a part of the path '/cache/youtubemetadata/[VIDEOID]/ytvideo.info.json'

### ISSUE THREAD

**Issue by wjbridge** [ankenyr/jellyfin-youtube-metadata-plugin#54]
Feel free to reopen the original issue #44. I am getting this same error.

I can also report this on `1.0.3.7`.
Docker Image: `https://github.com/linuxserver/docker-jellyfin`
Jellyfin Version: `10.8`

If I look at the cache folder which is `/config/cache` be default in the `linuxserver/docker-jellyfin` docker image, I cannot find the `youtubemetadata` folder. Should this be created by the plugin?

```
[21:08:23] [ERR] [43] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Episode at /youtube/Chris Titus Tech [youtube2-UCg6gPGh8HU2U01vaFCAsvmQ]/20220604 - What is your Daily Driver for Privacy feat. Techlore - [x43Clbsp3Rw].mp4
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/cache/youtubemetadata/x43Clbsp3Rw/ytvideo.info.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

More logs with debug (changed my cache directory to `/cache`
```
[21:28:28] [DBG] [23] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: Not Fresh: kZMoxUyumx0
[21:28:28] [DBG] [23] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDLEpisodeProvider: GetAndCacheMetadata
[21:28:28] [DBG] [11] MediaBrowser.Providers.TV.EpisodeMetadataService: Running YTDLEpisodeProvider for /youtube/Chris Titus Tech [youtube2-UCg6gPGh8HU2U01vaFCAsvmQ]/20220504 - Fixing my biggest failure - [nDlGkDENCyM].mp4
[21:28:28] [DBG] [11] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: /youtube/Chris Titus Tech [youtube2-UCg6gPGh8HU2U01vaFCAsvmQ]/20220504 - Fixing my biggest failure - [nDlGkDENCyM].mp4
[21:28:28] [DBG] [11] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: Not Fresh: nDlGkDENCyM
[21:28:28] [DBG] [11] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDLEpisodeProvider: GetAndCacheMetadata
[21:28:28] [DBG] [27] MediaBrowser.Providers.TV.EpisodeMetadataService: Running YTDLEpisodeProvider for /youtube/Chris Titus Tech [youtube2-UCg6gPGh8HU2U01vaFCAsvmQ]/20220514 - The Best Windows Tool for 2022 - [tPRv-ATUBe4].mp4
[21:28:28] [DBG] [27] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: /youtube/Chris Titus Tech [youtube2-UCg6gPGh8HU2U01vaFCAsvmQ]/20220514 - The Best Windows Tool for 2022 - [tPRv-ATUBe4].mp4
[21:28:28] [DBG] [27] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: Not Fresh: tPRv-ATUBe4
[21:28:28] [DBG] [27] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDLEpisodeProvider: GetAndCacheMetadata
[21:28:28] [DBG] [24] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/nDlGkDENCyM/ytvideo.info.json
[21:28:28] [DBG] [23] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/x6063EuxfEA/ytvideo.info.json
[21:28:28] [DBG] [13] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/MbCkFag4t_c/ytvideo.info.json
[21:28:28] [DBG] [10] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/x43Clbsp3Rw/ytvideo.info.json
[21:28:28] [DBG] [11] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/tPRv-ATUBe4/ytvideo.info.json
[21:28:28] [ERR] [13] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in YoutubeMetadata
System.IO.DirectoryNotFoundException: Could not find a part of the path '/cache/youtubemetadata/MbCkFag4t_c/ytvideo.info.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.IO.Abstractions.FileWrapper.ReadAllText(String path)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetMetadata(E info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[21:28:28] [ERR] [10] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in YoutubeMetadata
System.IO.DirectoryNotFoundException: Could not find a part of the path '/cache/youtubemetadata/x43Clbsp3Rw/ytvideo.info.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
```

**Comment by ankenyr** [comment]
Are you sure that this video is downloadable without a cookie? age restriction or anything?

**Comment by wjbridge** [comment]
Yup, I actually downloaded it already with yt using a docker container. I did not configure cookies to do that or age restriction.

**Comment by wjbridge** [comment]
Still have the same issue with `1.0.3.8`. I enabled the debug output to see if this helps.

```
[12:34:28] [DBG] [42] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: 20220622 - FIRST_REVIEW_Of_Intel_s_Desktop_ARC_GPU -
[12:34:28] [DBG] [39] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: 20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 -
[12:34:28] [DBG] [36] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: 20220629 - Do_NOT_Buy_Nvidia_s_New_GPU -
[12:34:28] [DBG] [42] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: /youtube
[12:34:28] [DBG] [36] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: /youtube
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: 20220627 - Nvidia_AMD_Won_t_Like_THIS -
[12:34:28] [DBG] [41] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: 20220701 - AMD_s_ADDING_Something_HUGE_To_RX_7000_GPUs -
[12:34:28] [DBG] [39] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: /youtube
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: /youtube
[12:34:28] [DBG] [41] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: /youtube
[12:34:28] [DBG] [42] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result:
[12:34:28] [DBG] [41] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result:
[12:34:28] [DBG] [36] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result:
[12:34:28] [DBG] [39] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result:
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result:
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalEpisodeProvider: YTLocal GetMetadata: /youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].mp4
[12:34:28] [ERR] [40] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in YoutubeMetadata
System.IO.FileNotFoundException: Could not find file '/youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].info.json'.
File name: '/youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].info.json'
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Jellyfin.Plugin.YoutubeMetadata.Utils.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeLocalProvider`2.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[12:34:28] [DBG] [40] MediaBrowser.Providers.TV.EpisodeMetadataService: Running EpisodeNfoProvider for /youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].mp4
[12:34:28] [DBG] [40] MediaBrowser.Providers.TV.EpisodeMetadataService: EpisodeNfoProvider returned no metadata for /youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].mp4
[12:34:28] [DBG] [40] MediaBrowser.Providers.TV.EpisodeMetadataService: Running YTDLEpisodeProvider for /youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].mp4
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: /youtube/20220624 - AMD_CONFIRMS_Insane_Specs_For_RX_7000 - [cq7FzV6y-bA].mp4
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: Not Fresh: cq7FzV6y-bA
[12:34:28] [DBG] [40] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDLEpisodeProvider: GetAndCacheMetadata
Unsupported codec with id 98314 for input stream 2
[12:34:28] [DBG] [34] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL ReadYTDLInfo: /cache/youtubemetadata/cq7FzV6y-bA/ytvideo.info.json
[12:34:28] [ERR] [34] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in YoutubeMetadata
System.IO.DirectoryNotFoundException: Could not find a part of the path '/cache/youtubemetadata/cq7FzV6y-bA/ytvideo.info.json'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.Abstractions.FileWrapper.ReadAllText(String path)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.ReadYTDLInfo(String fpath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetMetadata(E info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[12:34:28] [DBG] [35] MediaBrowser.Providers.TV.EpisodeMetadataService: Running YTDLImageProvider for /youtube/20220627 - Nvidia_AMD_Won_t_Like_THIS - [2DH1Wq-ZzdA].mp4
[12:34:28] [DBG] [35] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: YTDLImage GetImages: 20220627 - Nvidia_AMD_Won_t_Like_THIS -
[12:34:28] [DBG] [35] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: YTDLImage GetImages: {item.Name} is not fresh.
[12:34:28] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress 3a549504175c46b59beb8d76caa3c05b 80
[12:34:28] [ERR] [36] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Episode at /youtube/20220627 - Nvidia_AMD_Won_t_Like_THIS - [2DH1Wq-ZzdA].mp4
System.IO.DirectoryNotFoundException: Could not find a part of the path '/cache/youtubemetadata/2DH1Wq-ZzdA/ytvideo.info.json'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[12:34:28] [ERR] [8] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Episode at /youtube/20220701 - AMD_s_ADDING_Something_HUGE_To_RX_7000_GPUs - [rycJpyzvj3Y].mp4
```

**Comment by wjbridge** [comment]
Found out the problem. Somehow although I put `python3` to be installed; it was not installed correctly. I tried to execute `yt-dlp` in the container and saw an error message. I don't know if logging could be added that would return if `yt-dlp` showed an error.

**Comment by zinjacoder** [comment]
I am having the same issue with v1.0.3.15
yt-dlp is installed properly in the jf v10.11.10 container and is reporting its version just like @truppelito ( https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/54#issuecomment-3526633730 )

so, my guess, @wjbridge , is that this is not to be marked closed/completed.

please advise.

edit: version numbers
