### ISSUE TITLE
"youtube-dl not found on path"

### ISSUE THREAD

**Issue by cyberpunk2350** [ankenyr/jellyfin-youtube-metadata-plugin#88]
Running version 1.0.3.8 of the plugin, receiving the following error:
```
2023-08-02T00:41:56.223949954Z [00:41:56] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Error in YoutubeMetadata
2023-08-02T00:41:56.223993716Z System.IO.FileNotFoundException: youtube-dl not found on path!
2023-08-02T00:41:56.224004775Z    at NYoutubeDL.Services.PreparationService.SetupPrepare(YoutubeDLP ydl)
2023-08-02T00:41:56.224013411Z    at NYoutubeDL.Services.InfoService.GetDownloadInfoAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
2023-08-02T00:41:56.224021895Z    at NYoutubeDL.Services.PreparationService.PrepareDownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
2023-08-02T00:41:56.224030261Z    at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
2023-08-02T00:41:56.224038546Z    at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, String url, CancellationToken cancellationToken)
2023-08-02T00:41:56.224046955Z    at NYoutubeDL.YoutubeDLP.DownloadAsync(String videoUrl)
2023-08-02T00:41:56.224055249Z    at Jellyfin.Plugin.YoutubeMetadata.Utils.YTDLMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
2023-08-02T00:41:56.224063650Z    at Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLMovieProvider.GetAndCacheMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
2023-08-02T00:41:56.224072012Z    at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetMetadata(E info, CancellationToken cancellationToken)
2023-08-02T00:41:56.224080345Z    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by cyberpunk2350** [comment]
this is probably due to not having yt-dlp installed, disregard.
