### ISSUE TITLE
Readme say to use yt-dlp yet logs complain about youtube-dl

### ISSUE THREAD

**Issue by genebean** [ankenyr/jellyfin-youtube-metadata-plugin#98]
The readme says to use yt-dlp, which I am, but I see this in my log... why is it looking for youtube-dl?

```log
Dec 20 21:52:46 nixnuc jellyfin[662330]: [21:52:46] [ERR] [34] MediaBrowser.Providers.Manager.ProviderManager: YTDLImageProvider failed in GetImageInfos for type Movie at /var/lib/jellyfin/my-downloads/YouTube/Funny/Amazon Echo - SNL [YvT_gqs5ETk].mp4
Dec 20 21:52:46 nixnuc jellyfin[662330]: System.IO.FileNotFoundException: youtube-dl not found on path!
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.Services.PreparationService.SetupPrepare(YoutubeDLP ydl)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.Services.InfoService.GetDownloadInfoAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.Services.PreparationService.PrepareDownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.Services.DownloadService.DownloadAsync(YoutubeDLP ydl, String url, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at NYoutubeDL.YoutubeDLP.DownloadAsync(String videoUrl)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at Jellyfin.Plugin.YoutubeMetadata.Utils.YTDLMetadata(String id, IServerApplicationPaths appPaths, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
Dec 20 21:52:46 nixnuc jellyfin[662330]:    at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type) in /build/source/MediaBrowser.Providers/Manager/ProviderManager.cs:line 280
Dec 20 21:52:50 nixnuc jellyfin[662330]: [21:52:50] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 4 seconds
Dec 20 21:52:50 nixnuc jellyfin[662330]: [21:52:50] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

**Comment by ankenyr** [comment]
Likely because its not in the path. The error is coming from NYoutbeDL which is a dependency and they probably just wrote the error message as youtube-dl rather than youtube-dlp. If you are getting that error, its not able to find the binary.
